### ISSUE TITLE
Menu::all()->toTree()返回[]

### ISSUE THREAD

**Issue by jerryliu306** [jiaxincui/closure-table#10]
$multiTree = Menu::all()->toTree();

var_dump($multiTree);
返回[]

**Comment by jiaxincui** [comment]
如果你的 `Menu::all()` 返回的不是空数组，那么 `toTree()` 应该能生成正确的树形结构数组。
但请注意 `toTree()` 实际可以接收三个参数 `id` `parent` `children`，如果你的字段和默认不一样但话，你应该传入正确但字段值。
