### ISSUE TITLE
$menu->getRoot(); 返回为空

### ISSUE THREAD

**Issue by vFire** [jiaxincui/closure-table#12]
PHP7 Laravel5.8 自定义parent为parent_id：
使用$menu->getRoot();返回为空，但是改成getRoots就可以返回多节点，搞不懂是为什么，我想通过子节点获取它的root然后生成树，但是始终返回为空。

应用场景如下：存在大量节点的时候，考虑性能不能一次性展开所有节点，但是如果有初始访问节点，我希望展开以这个节点为脉络的所有父节点，其他节点默认保持关闭，等用户点击再展开。

**Comment by jiaxincui** [comment]
首先，`getRoot()`是实例方法，`Menu::getRoots()` 是静态方法，如果 `$menu`本身是root，通过 `$menu->getRoot()` 会返回 `null`，当然这个到底是应该返回自身还是`null`值得思考（后期版本会考虑）。

关于应用场景，完全可以通过 `getAncestors()` 获取到所有向上节点。
