### ISSUE TITLE
CollectionExtension toTree bug

### ISSUE THREAD

**Issue by wukangding** [jiaxincui/closure-table#19]
if (!isset($data[0][$parent])) {
            return [];
        }

换成
if (!key_exists($parent, $data[0])) {
            return [];
        }

**Comment by jiaxincui** [comment]
感谢提出问题

之所以用 `isset` 是因为考虑结果集为空的情况下, `data[0]` 会报错，使用 `isset($data[0][$parent])` 可以断定两种情况即 `$data[0]` 不存在或者 `$data[0][$parent]` 不存在
