### ISSUE TITLE
建议支持 id 可以为 UUID 或者 ULID

### ISSUE THREAD

**Issue by hihuangwei** [jiaxincui/closure-table#28]
建议支持 id 可以为 UUID 或者 ULID

**Comment by jiaxincui** [comment]
当前设计是支持 UUID 和 ULID 的

**Comment by jiaxincui** [comment]
3.0版本已支持

**Comment by hihuangwei** [comment]
![image](https://github.com/user-attachments/assets/65b15ce5-fadf-427c-9bbf-33be41c6249c)
![image](https://github.com/user-attachments/assets/6dd9137d-62b4-4f76-b61e-2838b832cf65)

`$menu = Department::find('id', '01he0brbw747rd5yd0teeayvgn');
        return $menu->perfectNode();`

依然存在问题
