### ISSUE TITLE
$product->getRoot()->getTree() doesnt work

### ISSUE THREAD

**Issue by TonsiTT** [jiaxincui/closure-table#31]
Hey, this is a great library and thanks for the effort.

I ran into an issue. For some reason this combination doesnt work for me

$product->getRoot(); //Works
$product->getTree(); // Works

$product->getBesideTree(); // doesn't Work

$product->getRoot()->getTree(); //doesnt work

**Comment by TonsiTT** [comment]
it works if i do this
>getRoots()->getTrees(['id', 'desc']);

**Comment by jiaxincui** [comment]
是的，这个问题确实存在，由于之前根节点 `parent` 默认为 `0` ，新的 3.0 版本已经更改了默认为 'null' ，已经修复，正在准备发布
