### ISSUE TITLE
存在表前缀情况下请fix下

### ISSUE THREAD

**Issue by Tamn9208** [jiaxincui/closure-table#9]
如果在laravel中设置了表前缀，
`$query = "
            INSERT INTO {$table} ({$ancestorColumn}, {$descendantColumn}, {$distance})
            SELECT tbl.{$ancestorColumn}, {$descendantId}, tbl.{$distance}+1
            FROM {$table} AS tbl
            WHERE tbl.{$descendantColumn} = {$ancestorId}
            UNION ALL
            SELECT {$descendantId}, {$descendantId}, 0
            ON DUPLICATE KEY UPDATE {$distance} = VALUES ({$distance})
        ";`
和
`public function getRoot(array $columns = ['*'])
    {
        $parentColumn = $this->getParentColumn();
        return $this
            ->joinRelationBy('ancestor')
            ->where($parentColumn, 0)
            ->orWhere(function ($query) use ($parentColumn) {
                $query->whereNull($parentColumn);
            })
            ->first($columns);
    }`
2种操作数据库方法会冲突，望处理下，3qs

**Comment by jiaxincui** [comment]
虽然没弄明白你表述的需求，但我想是这样的。
如果存在表前缀的情况下，可以在你的模型里定义一个 `closureTable` 属性指定表名。

**Comment by Tamn9208** [comment]
> 虽然没弄明白你表述的需求，但我想是这样的。
> 如果存在表前缀的情况下，可以在你的模型里定义一个 `closureTable` 属性指定表名。

模型调用的类，类其中2个方法一个可以用前缀，一个不能用前缀

**Comment by jiaxincui** [comment]
明白了，感谢反馈，这个问题在下个版本将会修复。

**Comment by jiaxincui** [comment]
已修复
